import { Router, type Request, type Response } from "express";
import { logger } from "../../lib/logger.js";

const router = Router();

const UPSTREAM_UA =
  "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36";

export function encodeParam(s: string): string {
  return Buffer.from(s, "utf8").toString("base64url");
}

function decodeParam(s: string): string {
  return Buffer.from(s, "base64url").toString("utf8");
}

function resolveContentType(raw: string, firstBytes?: Uint8Array): string {
  if (raw === "video/mkv" || raw === "video/x-mkv") return "video/x-matroska";

  if (raw && raw !== "application/octet-stream" && raw !== "binary/octet-stream") {
    return raw;
  }

  if (firstBytes && firstBytes.length >= 8) {
    if (firstBytes[0] === 0x1a && firstBytes[1] === 0x45 &&
        firstBytes[2] === 0xdf && firstBytes[3] === 0xa3) {
      return "video/x-matroska";
    }
    if (firstBytes[4] === 0x66 && firstBytes[5] === 0x74 &&
        firstBytes[6] === 0x79 && firstBytes[7] === 0x70) {
      return "video/mp4";
    }
    if (firstBytes[0] === 0x47) return "video/mp2t";
  }

  return "video/mp4";
}

// ─── Kartoons range-request proxy ─────────────────────────────────────────────
// Kartoons CDN URLs are IP-bound to our server's IP at the time the URL is
// generated by the Kartoons addon. Routing through /karproxy ensures every
// segment request originates from the same IP so the CDN token stays valid.
// Also adds CODECS= to HLS master playlists when missing, which is required
// by strict HLS players (LG WebOS) to initialise the video decoder.
router.all("/karproxy", async (req: Request, res: Response) => {
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Headers", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "GET" && req.method !== "HEAD") {
    res.status(405).end();
    return;
  }

  const { u } = req.query as Record<string, string | undefined>;
  if (!u) { res.status(400).json({ error: "Missing u param" }); return; }

  let targetUrl: string;
  try {
    targetUrl = decodeParam(u);
    new URL(targetUrl);
  } catch {
    res.status(400).json({ error: "Invalid u param" });
    return;
  }

  const t0 = Date.now();
  const range = req.headers["range"];

  const upstreamHeaders: Record<string, string> = {
    "user-agent": UPSTREAM_UA,
    "accept": "*/*",
    "accept-encoding": "identity",
  };
  if (range) upstreamHeaders["range"] = range;

  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "*");
  res.setHeader("Access-Control-Expose-Headers", "Content-Range, Accept-Ranges, Content-Length");

  let upstream: globalThis.Response;
  try {
    upstream = await fetch(targetUrl, {
      headers: upstreamHeaders,
      redirect: "follow",
      signal: AbortSignal.timeout(60_000),
    });
  } catch (err) {
    logger.error({ err, targetUrl }, "KTProxy: upstream fetch failed");
    if (!res.headersSent) res.status(502).end();
    return;
  }

  if (upstream.status >= 400) {
    logger.warn({ targetUrl, status: upstream.status }, "KTProxy: upstream error");
    res.status(upstream.status).end();
    return;
  }

  if (req.method === "HEAD") {
    const rawCtHead = upstream.headers.get("content-type") ?? "";
    res.setHeader("Content-Type", resolveContentType(rawCtHead));
    res.setHeader("Accept-Ranges", "bytes");
    const clHead = upstream.headers.get("content-length");
    if (clHead) res.setHeader("Content-Length", clHead);
    const crHead = upstream.headers.get("content-range");
    if (crHead) res.setHeader("Content-Range", crHead);
    res.setHeader("Cache-Control", "no-store");
    res.removeHeader("Content-Disposition");
    res.status(upstream.status);
    upstream.body?.cancel().catch(() => {});
    res.end();
    return;
  }

  if (!upstream.body) {
    res.setHeader("Content-Type", resolveContentType(upstream.headers.get("content-type") ?? ""));
    res.setHeader("Accept-Ranges", "bytes");
    res.setHeader("Cache-Control", "no-store");
    res.removeHeader("Content-Disposition");
    res.status(upstream.status);
    res.end();
    return;
  }

  const reader = upstream.body.getReader();
  req.on("close", () => reader.cancel().catch(() => {}));

  let firstChunk: Uint8Array | undefined;
  try {
    const { done, value } = await reader.read();
    if (!done && value?.length) firstChunk = value;
  } catch { /* stream ended early */ }

  const rawKtCt = upstream.headers.get("content-type") ?? "";
  const contentType = resolveContentType(rawKtCt, firstChunk);

  res.setHeader("Content-Type", contentType);
  res.setHeader("Accept-Ranges", "bytes");

  const contentRange = upstream.headers.get("content-range");
  if (contentRange) res.setHeader("Content-Range", contentRange);

  res.setHeader("Cache-Control", "no-store");
  res.removeHeader("Content-Disposition");

  const isHls = contentType.includes("mpegurl") || targetUrl.includes(".m3u8");
  if (isHls) {
    const hlsChunks: Uint8Array[] = [];
    if (firstChunk?.length) hlsChunks.push(firstChunk);
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        hlsChunks.push(value);
      }
    } catch { /* ignore early close */ }

    let playlist = Buffer.concat(hlsChunks).toString("utf8");

    // Kartoons streams are H.264 High Profile Level 4.0 + AAC.
    // Inject CODECS= when missing so strict HLS players initialise the decoder.
    if (playlist.includes("#EXT-X-STREAM-INF") && !playlist.includes("CODECS=")) {
      playlist = playlist.replace(
        /#EXT-X-STREAM-INF:([^\n\r]*)/g,
        (_match, attrs: string) => `#EXT-X-STREAM-INF:${attrs},CODECS="avc1.640028,mp4a.40.2"`,
      );
    }

    const hlsBody = Buffer.from(playlist, "utf8");
    res.setHeader("Content-Length", hlsBody.length);
    res.status(upstream.status);
    logger.info(
      { targetUrl, status: upstream.status, bytesSent: hlsBody.length, durationMs: Date.now() - t0 },
      "KTProxy: done (m3u8 rewrite)",
    );
    res.end(hlsBody);
    return;
  }

  const contentLength = upstream.headers.get("content-length");
  if (contentLength) res.setHeader("Content-Length", contentLength);

  res.status(upstream.status);

  let bytesSent = 0;
  try {
    if (firstChunk?.length && !res.destroyed) {
      res.write(Buffer.from(firstChunk));
      bytesSent += firstChunk.byteLength;
    }
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (res.destroyed) break;
      res.write(Buffer.from(value));
      bytesSent += value.byteLength;
    }
  } catch (err) {
    logger.warn({ err, targetUrl }, "KTProxy: pipe interrupted");
  }

  logger.info({ targetUrl, status: upstream.status, bytesSent, durationMs: Date.now() - t0 }, "KTProxy: done");
  res.end();
});

export default router;
